### ISSUE TITLE
Download don't work on explore or search page

### ISSUE THREAD

**Issue by DineshSolanki** [sixem/tiktok-download-buttons#17]
The download starts and fails when clicked on search or explore page, like the following page
![image](https://github.com/sixem/tiktok-download-buttons/assets/15937452/c086e60a-e6f8-4c27-8863-1ffaef1ebf74)
it will fail, following screenshots for failure -
![image](https://github.com/sixem/tiktok-download-buttons/assets/15937452/71442d41-8c95-4d6d-a8ca-940aa8f76b78)
![image](https://github.com/sixem/tiktok-download-buttons/assets/15937452/b52ee031-d754-4188-bf01-b713971bd009)
 - [Link for reference](https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c001-euttp/oAeEgbs7dQfRnNZRAGdDAsBPFDL8gVKSlQOj8y/?a=1988&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C&cv=1&br=4330&bt=2165&bti=NDU3ZjAwOg%3D%3D&cs=0&ds=6&ft=4KJMyMkQ8Zmo0wCcM94jVCRbdpWrKsd.&mime_type=video_mp4&qs=0&rc=ODM3NzhnZGZnZzk8Njc4NUBpM245Zzo6ZmVmbjMzZjczM0AtYl5iLl9iXjQxNGI0NmA0YSMxYjFgcjQwNGtgLS1kMWNzcw%3D%3D&btag=e00088000&expire=1710769199&l=20240316133935D1869F77E366EA23D189&ply_type=2&policy=2&signature=8c44409a53f04d541dd6f361d2690ac3&tk=tt_chain_token)
the only way to download with this is when I follows following -

1. Click the video, so that you can only see this video (the download will fail here also) -
![image](https://github.com/sixem/tiktok-download-buttons/assets/15937452/47efe049-81ec-4dd6-ab59-cb80f4883e65)
2. Now refresh the page, or open in new tab at step 1, so that the player goes landscape
![image](https://github.com/sixem/tiktok-download-buttons/assets/15937452/8a087e20-6cde-4063-8e26-066250f7490e)
3. Click the download button, an it downloads successfully.

**Comment by sixem** [comment]
Hi,

Is this the same issue as #16?

I've attempted to update it, and I'm just waiting on it to be published. Basically, the API was outdated, and the fallback method isn't very reliable.

**Comment by DineshSolanki** [comment]
> Hi,
> 
> Is this the same issue as #16?
> 
> I've attempted to update it, and I'm just waiting on it to be published. Basically, the API was outdated, and the fallback method isn't very reliable.

No they are different, the api and the fallback both don't work, until i can see video full screen on page.

There is no access denied error on fallback page, only the error that media type not supported as visible in screenshot

**Comment by sixem** [comment]
> > Hi,
> > Is this the same issue as #16?
> > I've attempted to update it, and I'm just waiting on it to be published. Basically, the API was outdated, and the fallback method isn't very reliable.
> 
> No they are different, the api and the fallback both don't work, until i can see video full screen on page.
> 
> There is no access denied error on fallback page, only the error that media type not supported as visible in screenshot

Yeah, but the fallback can behave in different ways depending on the video. Sometimes it can give an access denied message, and sometimes it may just fail instead. It can depend on the video, date uploaded, how it's viewed et cetera.

If you could test it again once the update is live, that'd be great — version `1.1.6` that is. It should fix the issues with the API. If it still fails after that, I'll have another look when I can.

**Comment by DineshSolanki** [comment]
@sixem tried 1.1.6 still the same issue, for more detail the toaster says "fetch not allowed" and in the new tab, request shows 403
![image](https://github.com/sixem/tiktok-download-buttons/assets/15937452/896629ba-ee3e-4701-9665-ec530d06081b)
